#!/bin/bash
echo "🔑 API KEY SETUP REMINDER"
echo "========================"
echo ""
echo "1. Copy .env.example to .env:"
echo "   cp .env.example .env"
echo ""
echo "2. Get your API keys:"
echo "   - CoinDCX: https://coindcx.com/api-dashboard"
echo "   - ZebPay: https://zebpay.com/api"
echo ""
echo "3. Edit .env and add your keys"
echo ""
echo "4. NEVER commit .env to Git!"
